spring:
  application:
    name: jpa
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3308/pregrancytracker}
    username: ${MYSQL_ADMIN_USER:root}
    password: ${MYSQL_ADMIN_PASS:123456}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB

custom:
  redis:
    host: ${REDIS_URL:localhost}
    port: ${REDIS_PORT:6379}

jwt:
  key: pYL/bFa3qdmZC52COcG3UO/Xd+vjJgpo42ucD7WRJRQ=

upload:
  path: C:\Users\DELL\Desktop\images
server:
  port: 8081
openapi:
  service:
    api-docs: api-service
    server: http://localhost:8080
    title: API Service
    version: 1.0.0


