spring:
  application:
    name: jpa
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/pregrancytracker}
    username: ${MYSQL_ADMIN_USER:root}
    password: ${MYSQL_ADMIN_PASS:123456}
  jpa:
    hibernate:
      ddl-auto: none
      #Name of column in entity is equal with name in mysql
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB

server:
  port: 8081
  address: 0.0.0.0

custom:
  redis:
    host: ${REDIS_URL:localhost}
    port: ${REDIS_PORT:6379}

jwt:
  key: N3XlRl/GXHuZo2oepmSjKopRTYGGZAX7NhMEyrE3LxQYUbep/6cxK4siBnKwLUL5

upload:
  path: C:\Users\DELL\Desktop\images

openapi:
  service:
    api-docs: api-service
    server: http://localhost:8081
    title: API Service
    version: 1.0.0

mailServer:
  host: smtp.gmail.com
  port: 587
  email: superanhziggy@gmail.com
  password: nhvx myku cczo nyao
  protocol: smtp
  isSSL: true

paypal:
  client:
    id: ARjqT5-IHMjP5GWgXTNZGOcUr-HWbv-_s5zKuFCvb8s21B2aoMb6swsUad1n-abMlB2DVbRDz-7t5knH
    secret: EPB-2LYBeZ2ZaWLFnKIU3dPZSqn17D_lsAW1jE1vyv5LNCyysmtQBjgLB7ECSOOj9VXUr5DJ8VV4uipq
  mode: sandbox  # Hoặc "live" khi chạy thực tế
  base-url: https://api-m.sandbox.paypal.com